### Healthcheck

GET http://0.0.0.0:8086/live


###


GET http://0.0.0.0:8086/ready




### Category

POST http://localhost:8080/products/category

{
    "id":5,
    "name":"Cat6"
}

###

GET http://localhost:8080/products/category/5


###

GET http://localhost:8080/products/categories


###

PUT http://localhost:8080/products/category

{
    "id":4,
    "name":"Cat5"
}

###

DELETE http://localhost:8080/products/category/1



### Product 


POST http://localhost:8080/products/product

{
    "id":1,
    "name":"Prod1",
    "categoryId":2,
    "price":10000,
    "discount":0
}

###

GET http://localhost:8080/products//product/1


###

GET http://localhost:8090/products/2


###

PUT http://localhost:8080/products/product

{
    "id":1,
    "name":"Product1"
}

###

DELETE http://localhost:8080/products/product/1


