version: '3'
services:
    products:
       build:    
         context: .
         dockerfile: Dockerfile
       restart: on-failure  
       ports:
         - $API_PORT:$API_PORT
       environment:
          - GIN_MODE=$GIN_MODE
          - API_SECRET=$API_SECRET   
          - DB_HOST=$DB_HOST
          - DB_PORT=$DB_PORT
          - DB_USER=$DB_USER
          - DB_PASS=$DB_PASSWORD
          - DB_NAME=$DB_NAME
          - API_PORT=$API_PORT
       depends_on:
          - mysql
          - phpmyadmin
       networks:
         - back-end

    mysql:
      image: mysql:latest
      hostname: $DB_HOST
      restart: always
      ports:
       - 3366:3306
      environment:
        - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
        - MYSQL_DATABASE=$DB_NAME
        - MYSQL_USER=$DB_USER
        - MYSQL_PASSWORD=$DB_PASSWORD
      volumes:
         - db_data:/var/lib/mysql
         - ./src/main/resources/db/init.sql:/data/application/init.sql
      command: --init-file /data/application/init.sql
      networks:
         - back-end
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      links:
        - mysql:db
      ports:
        - 8081:8081

volumes:
      db_data: 
networks:
  back-end:
      

