version: '3'
services:
    app:
       build:    
         context: .
         dockerfile: Dockerfile
       restart: always
       ports:
         - 8080:8080
       environment:
          - GIN_MODE=$GIN_MODE
          - APP_PORT=$APP_PORT
          - API_SECRET=$API_SECRET   
          - DB_HOST=$DB_HOST
          - DB_PORT=$DB_PORT
          - DB_USER=$DB_USER
          - DB_PASS=$DB_PASSWORD
          - DB_NAME=$DB_NAME
          - API_PORT=$API_PORT
       depends_on:
          - db

    db:
      image: mysql:latest
      restart: always
      ports:
       - 3366:3306
      environment:
        - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
        - MYSQL_DATABASE=$DB_NAME
        - MYSQL_USER=$DB_USER
        - MYSQL_PASSWORD=$DB_PASSWORD
      volumes:
         - db_data:/var/lib/mysql

volumes:
      db_data: 
      

